### ISSUE TITLE
Trouble with setup

### ISSUE THREAD

**Issue by RockinRich** [MitchTalmadge/discord-echobot#21]
I am having trouble setting up my program. After I 'npm start' I get the following error message. Any tips would be greatly appreciated, thank you!
<img width="945" alt="Screenshot 2021-02-11 140225" src="https://user-images.githubusercontent.com/78929709/107685271-cceb2980-6c71-11eb-8371-945d5e47a0d1.png">

**Comment by MitchTalmadge** [comment]
Make sure you run both `npm install` and `npm run build` before trying to run `npm start`. You only have to do it one time, then `npm start` will work each time :)

**Comment by RockinRich** [comment]
Thank you for your quick reply!! I did that now I am getting another error message, it is saying I have an unexpected token. 
<img width="619" alt="screenshot2" src="https://user-images.githubusercontent.com/78929709/107686102-c8734080-6c72-11eb-9d5b-253d65779871.png">

**Comment by MitchTalmadge** [comment]
No problem! The error you show now is due to your configuration file. It is not valid JSON. You can use this tool online to help write your config file and make sure it is error free: https://codebeautify.org/jsonvalidator

If you can't figure it out, post your config with the token blanked out and I will help!

**Comment by RockinRich** [comment]
You're the man. Thank you for being patient!

**Comment by MitchTalmadge** [comment]
Of course, enjoy! Let me know if you need more help.
